services:
  postgres:
    image: postgres:18
    container_name: keycloak_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      # Webhook HTTP configuration
      WEBHOOK_HTTP_BASE_PATH: ${WEBHOOK_HTTP_BASE_PATH}
      WEBHOOK_EVENTS_TAKEN: ${WEBHOOK_EVENTS_TAKEN}
      WEBHOOK_HTTP_AUTH_USERNAME: ${WEBHOOK_USERNAME}
      WEBHOOK_HTTP_AUTH_PASSWORD: ${WEBHOOK_PASSWORD}

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - start-dev
    volumes:
      - ./keycloak-themes/Wealthyfy-Theme:/opt/keycloak/themes/Wealthyfy-Theme:Z
      - ./keycloak-extensions:/opt/keycloak/providers:ro
    networks:
      - keycloak_net

volumes:
  keycloak_db_data:

networks:
  keycloak_net:
    driver: bridge
