"""added new columns in fip id master table

Revision ID: 000d8e12d5fb
Revises: 610116a82df0
Create Date: 2025-11-20 15:38:10.549187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000d8e12d5fb'
down_revision: Union[str, Sequence[str], None] = '610116a82df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_institutions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('financial_institutions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_institutions', 'updated_at')
    op.drop_column('financial_institutions', 'created_at')
    # ### end Alembic commands ###
