"""rename the column name

Revision ID: 105c39187934
Revises: 000d8e12d5fb
Create Date: 2025-11-20 16:07:12.524705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '105c39187934'
down_revision: Union[str, Sequence[str], None] = '000d8e12d5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_institutions', sa.Column('Status', sa.Enum('ACTIVE', 'INACTIVE', name='financial_institutions_status_enum'), nullable=False))
    op.drop_index(op.f('ix_financial_institutions_consent'), table_name='financial_institutions')
    op.create_index(op.f('ix_financial_institutions_Status'), 'financial_institutions', ['Status'], unique=False)
    op.drop_column('financial_institutions', 'consent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_institutions', sa.Column('consent', postgresql.ENUM('ACTIVE', 'INACTIVE', name='financial_institutions_status_enum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_financial_institutions_Status'), table_name='financial_institutions')
    op.create_index(op.f('ix_financial_institutions_consent'), 'financial_institutions', ['consent'], unique=False)
    op.drop_column('financial_institutions', 'Status')
    # ### end Alembic commands ###
