"""add new table for cancellation logs

Revision ID: 20ad9b8cc3d1
Revises: 3474fcc9cf80
Create Date: 2025-11-18 11:37:12.945260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ad9b8cc3d1'
down_revision: Union[str, Sequence[str], None] = '3474fcc9cf80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_cancellation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_request_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('cancelled_by', sa.Enum('USER', 'SYSTEM', name='cancelledby'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_request_id'], ['consent_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consent_cancellation_log')
    # ### end Alembic commands ###
