"""add new table pancard

Revision ID: 29589d46e1b2
Revises: 87c96d4824a0
Create Date: 2025-11-06 14:12:20.569646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29589d46e1b2'
down_revision: Union[str, Sequence[str], None] = '87c96d4824a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pancard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pancard', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'NOTVERIFIED', name='pancardstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pancard_id'), 'pancard', ['id'], unique=False)
    op.create_index(op.f('ix_pancard_user_id'), 'pancard', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pancard_user_id'), table_name='pancard')
    op.drop_index(op.f('ix_pancard_id'), table_name='pancard')
    op.drop_table('pancard')
    # ### end Alembic commands ###
