"""new table for storing deposite and term deposite data

Revision ID: 3a0b708bbf69
Revises: c87882e1204b
Create Date: 2025-11-21 15:41:59.812545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0b708bbf69'
down_revision: Union[str, Sequence[str], None] = 'c87882e1204b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banking_account_details',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_od_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('drawing_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('facility', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('account_sub_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('balance_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('micr_code', sa.String(length=20), nullable=True),
    sa.Column('pending_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pending_transaction_type', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['account_summaries.id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('term_deposit_details',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('compounding_frequency', sa.String(length=50), nullable=True),
    sa.Column('interest_computation', sa.String(length=50), nullable=True),
    sa.Column('interest_on_maturity', sa.String(length=100), nullable=True),
    sa.Column('interest_payout', sa.String(length=50), nullable=True),
    sa.Column('interest_periodic_payout_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('maturity_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recurring_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recurring_deposit_day', sa.Integer(), nullable=True),
    sa.Column('tenure_days', sa.Integer(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('tenure_years', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['account_summaries.id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_deposit_details')
    op.drop_table('banking_account_details')
    op.drop_table('account_summaries')
    # ### end Alembic commands ###
