"""update the user table

Revision ID: 4e79068b8c6d
Revises: 59e7345b89ed
Create Date: 2025-11-03 10:24:01.602871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e79068b8c6d'
down_revision: Union[str, Sequence[str], None] = '59e7345b89ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keycloak_user_id', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_keycloak_user_id'), 'users', ['keycloak_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_keycloak_user_id'), table_name='users')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'keycloak_user_id')
    # ### end Alembic commands ###
