"""new column to store the raw path

Revision ID: 5a693dd1a531
Revises: 105c39187934
Create Date: 2025-11-21 10:42:40.157204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a693dd1a531'
down_revision: Union[str, Sequence[str], None] = '105c39187934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consent_data_session', sa.Column('consent_file_path', sa.String(length=255), nullable=True, comment='Path to the stored consent file, if applicable'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consent_data_session', 'consent_file_path')
    # ### end Alembic commands ###
