"""create FIp id new table

Revision ID: 610116a82df0
Revises: 20ad9b8cc3d1
Create Date: 2025-11-20 15:33:56.288188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610116a82df0'
down_revision: Union[str, Sequence[str], None] = '20ad9b8cc3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fip_id', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.String(length=50), nullable=False),
    sa.Column('consent', sa.Enum('ACTIVE', 'INACTIVE', name='financial_institutions_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_institutions_consent'), 'financial_institutions', ['consent'], unique=False)
    op.create_index(op.f('ix_financial_institutions_fip_id'), 'financial_institutions', ['fip_id'], unique=True)
    op.create_index(op.f('ix_financial_institutions_id'), 'financial_institutions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_institutions_id'), table_name='financial_institutions')
    op.drop_index(op.f('ix_financial_institutions_fip_id'), table_name='financial_institutions')
    op.drop_index(op.f('ix_financial_institutions_consent'), table_name='financial_institutions')
    op.drop_table('financial_institutions')
    # ### end Alembic commands ###
