"""add new column

Revision ID: acccb497fc48
Revises: bec537030a15
Create Date: 2025-11-10 15:31:13.621570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acccb497fc48'
down_revision: Union[str, Sequence[str], None] = 'bec537030a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pancard', sa.Column('pancard_hash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_pancard_pancard_hash'), 'pancard', ['pancard_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pancard_pancard_hash'), table_name='pancard')
    op.drop_column('pancard', 'pancard_hash')
    # ### end Alembic commands ###
