"""new table for storinig financial account

Revision ID: ad2b6b94d393
Revises: 5a693dd1a531
Create Date: 2025-11-21 15:09:05.922282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2b6b94d393'
down_revision: Union[str, Sequence[str], None] = '5a693dd1a531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_accounts',
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=True),
    sa.Column('fip_id', sa.String(length=100), nullable=True),
    sa.Column('link_ref_number', sa.String(length=64), nullable=True),
    sa.Column('masked_account_number', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.Enum('DEPOSIT', 'TERM_DEPOSIT', 'MUTUAL_FUNDS', 'ETF', 'EQUITY_SHARES', name='fitypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consent_request.id'], ),
    sa.ForeignKeyConstraint(['fip_id'], ['financial_institutions.fip_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_financial_accounts_account_id'), 'financial_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_account_type'), 'financial_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_financial_accounts_consent_id'), 'financial_accounts', ['consent_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_fip_id'), 'financial_accounts', ['fip_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_link_ref_number'), 'financial_accounts', ['link_ref_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_accounts_link_ref_number'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_fip_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_consent_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_type'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    # ### end Alembic commands ###
