"""create_all_tables

Revision ID: aed6f6e0380b
Revises: 
Create Date: 2025-11-26 14:47:06.933494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed6f6e0380b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fip_id', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.String(length=50), nullable=False),
    sa.Column('Status', sa.Enum('ACTIVE', 'INACTIVE', name='financial_institutions_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_institutions_Status'), 'financial_institutions', ['Status'], unique=False)
    op.create_index(op.f('ix_financial_institutions_fip_id'), 'financial_institutions', ['fip_id'], unique=True)
    op.create_index(op.f('ix_financial_institutions_id'), 'financial_institutions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keycloak_user_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_setup_complete', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_keycloak_user_id'), 'users', ['keycloak_user_id'], unique=True)
    op.create_table('pancard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pancard', sa.String(length=255), nullable=False),
    sa.Column('pancard_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'NOTVERIFIED', name='pancardstatus'), nullable=False),
    sa.Column('consent', sa.Enum('YES', 'NO', name='consent_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pancard_consent'), 'pancard', ['consent'], unique=False)
    op.create_index(op.f('ix_pancard_id'), 'pancard', ['id'], unique=False)
    op.create_index(op.f('ix_pancard_pancard_hash'), 'pancard', ['pancard_hash'], unique=True)
    op.create_index(op.f('ix_pancard_user_id'), 'pancard', ['user_id'], unique=True)
    op.create_table('consent_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', 'EXPIRED', 'REJECTED', 'PAUSED', name='consentstatus'), nullable=False),
    sa.Column('consent_mode', sa.String(length=20), nullable=False),
    sa.Column('vua', sa.String(length=50), nullable=False),
    sa.Column('purpose_code', sa.String(length=10), nullable=False),
    sa.Column('purpose_text', sa.String(length=255), nullable=False),
    sa.Column('purpose_ref_uri', sa.String(length=512), nullable=True),
    sa.Column('purpose_category_type', sa.String(length=100), nullable=True),
    sa.Column('fetch_type', sa.Enum('ONETIME', 'PERIODIC', name='fetchtype'), nullable=False),
    sa.Column('data_range_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_range_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_life_unit', sa.Enum('HOUR', 'DAY', 'MONTH', 'YEAR', 'INF', name='unitenum'), nullable=False),
    sa.Column('data_life_value', sa.Integer(), nullable=False),
    sa.Column('frequency_unit', sa.Enum('HOUR', 'DAY', 'MONTH', 'YEAR', 'INF', name='unitenum'), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('redirect_url', sa.String(length=512), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('consent_types', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pan_id'], ['pancard.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_request_consent_id'), 'consent_request', ['consent_id'], unique=True)
    op.create_index(op.f('ix_consent_request_vua'), 'consent_request', ['vua'], unique=False)
    op.create_table('consent_fi_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_request_id', sa.Integer(), nullable=False),
    sa.Column('fi_type', sa.Enum('DEPOSIT', 'TERM_DEPOSIT', 'MUTUAL_FUNDS', 'ETF', 'EQUITY_SHARES', name='fi_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRE', name='consent_fi_type_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['consent_request_id'], ['consent_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_fi_type_consent_request_id'), 'consent_fi_type', ['consent_request_id'], unique=False)
    op.create_index(op.f('ix_consent_fi_type_fi_type'), 'consent_fi_type', ['fi_type'], unique=False)
    op.create_index(op.f('ix_consent_fi_type_id'), 'consent_fi_type', ['id'], unique=False)
    op.create_index(op.f('ix_consent_fi_type_status'), 'consent_fi_type', ['status'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=True),
    sa.Column('fip_id', sa.String(length=100), nullable=True),
    sa.Column('link_ref_number', sa.String(length=64), nullable=True),
    sa.Column('masked_account_number', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.Enum('DEPOSIT', 'TERM_DEPOSIT', 'MUTUAL_FUNDS', 'ETF', 'EQUITY_SHARES', name='fitypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consent_request.id'], ),
    sa.ForeignKeyConstraint(['fip_id'], ['financial_institutions.fip_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_account_type'), 'financial_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_financial_accounts_consent_id'), 'financial_accounts', ['consent_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_fip_id'), 'financial_accounts', ['fip_id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_link_ref_number'), 'financial_accounts', ['link_ref_number'], unique=False)
    op.create_table('account_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_holders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('holder_type', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('ckyc_compliance', sa.Boolean(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nominee_status', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_holders_account_id'), 'account_holders', ['account_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('transaction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_data_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('consent_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'COMPLETED', 'EXPIRED', 'FAILED', name='data_session_status_enum'), nullable=False),
    sa.Column('data_range_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_range_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('consent_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consent_request_id'], ['consent_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_data_session_session_id'), 'consent_data_session', ['session_id'], unique=True)
    op.create_index(op.f('ix_consent_data_session_consent_request_id'), 'consent_data_session', ['consent_request_id'], unique=False)
    op.create_index(op.f('ix_consent_data_session_status'), 'consent_data_session', ['status'], unique=False)
    op.create_table('consent_cancellation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_request_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('cancelled_by', sa.Enum('USER', 'SYSTEM', name='cancelledby'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_request_id'], ['consent_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banking_account_details',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_od_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('drawing_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('facility', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('account_sub_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('balance_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('micr_code', sa.String(length=20), nullable=True),
    sa.Column('pending_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pending_transaction_type', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['account_summaries.id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('term_deposit_details',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('compounding_frequency', sa.String(length=50), nullable=True),
    sa.Column('interest_computation', sa.String(length=50), nullable=True),
    sa.Column('interest_on_maturity', sa.String(length=100), nullable=True),
    sa.Column('interest_payout', sa.String(length=50), nullable=True),
    sa.Column('interest_periodic_payout_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('maturity_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recurring_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('recurring_deposit_day', sa.Integer(), nullable=True),
    sa.Column('tenure_days', sa.Integer(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('tenure_years', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['account_summaries.id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_deposit_details')
    op.drop_table('banking_account_details')
    op.drop_table('consent_cancellation_log')
    op.drop_index(op.f('ix_consent_data_session_status'), table_name='consent_data_session')
    op.drop_index(op.f('ix_consent_data_session_consent_request_id'), table_name='consent_data_session')
    op.drop_index(op.f('ix_consent_data_session_session_id'), table_name='consent_data_session')
    op.drop_table('consent_data_session')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_account_holders_account_id'), table_name='account_holders')
    op.drop_table('account_holders')
    op.drop_table('account_summaries')
    op.drop_index(op.f('ix_consent_request_vua'), table_name='consent_request')
    op.drop_index(op.f('ix_consent_request_consent_id'), table_name='consent_request')
    op.drop_table('consent_request')
    op.drop_index(op.f('ix_financial_accounts_link_ref_number'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_fip_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_consent_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_type'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_consent_fi_type_status'), table_name='consent_fi_type')
    op.drop_index(op.f('ix_consent_fi_type_id'), table_name='consent_fi_type')
    op.drop_index(op.f('ix_consent_fi_type_fi_type'), table_name='consent_fi_type')
    op.drop_index(op.f('ix_consent_fi_type_consent_request_id'), table_name='consent_fi_type')
    op.drop_table('consent_fi_type')
    op.drop_index(op.f('ix_pancard_user_id'), table_name='pancard')
    op.drop_index(op.f('ix_pancard_pancard_hash'), table_name='pancard')
    op.drop_index(op.f('ix_pancard_id'), table_name='pancard')
    op.drop_index(op.f('ix_pancard_consent'), table_name='pancard')
    op.drop_table('pancard')
    op.drop_index(op.f('ix_users_keycloak_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_financial_institutions_id'), table_name='financial_institutions')
    op.drop_index(op.f('ix_financial_institutions_fip_id'), table_name='financial_institutions')
    op.drop_index(op.f('ix_financial_institutions_Status'), table_name='financial_institutions')
    op.drop_table('financial_institutions')
    # ### end Alembic commands ###
