ACTIVE = "active"
INACTIVE = "inactive"
DELETED = "deleted"
CAP_ACTIVE = "ACTIVE"
CAP_INACTIVE = "INACTIVE"
CAP_DELETED = "DELETED"
VERIFIED="VERIFIED"
NOTVERIFIED="NOTVERIFIED"
SUCCESS="success"
FAILED="failed"
APPROVED="approved"
PENDING="pending"

# Transaction type constants
TRANSACTION_TYPE_CREDIT = "CREDIT"
TRANSACTION_TYPE_DEBIT = "DEBIT"

# Date format constants
DATE_FORMAT_YYYY_MM_DD = "%Y-%m-%d"